name: deploy on push
on: [push]

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v3
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
          host: 27.145.184.25
          username: ubuntu
          port: 22
          key: -----BEGIN RSA PRIVATE KEY----- MIIEowIBAAKCAQEAn2fLFKuzkgGidHts2OvhA0jACX00XSwefKaRldU+xkkxNW/Q bMTiXrYoGbdpBJTtpzF/Y/ZJFmxl6T3BJCJfF/vBsceFCxRaGnsBuAvinyCvVJfr xcUJBsDGqIy/zx7ucm8ciEcGVJL7GwQhZufq9s0uYEsGRs0+PDzCrtzGMSckgGBv xZeAzUK/+tRR+HkklnqAs32yXMv65tkFBFd58BwXG7ODRSjROr9jVUN6FVQkrUgx vx4ENQQ/BRgMVqWIuIVXBRIYZT0KpZTqCP1C4BXFLH3Xp2dK/S5V+oPR2SGPEesS RsuDwn9PYapGwoCQ//CbEvTqC154jOO/WoL8dQIDAQABAoIBADwKj06o4clT/knb l4MZTba790FbvJZ/oLgY0WtbV/q95OAYzqu5eP5tpCsTj2XfZqh8F1yijqL4j2ZM EWy32ZOiCzIYUb97mfixblNRfrmrSP8W/gKPFbhKcklYQoMURoIp4dhe0D6Y4iYp 5x7oqfLuE9LHT4Tpl9B+nmHY3Hn0iRIf0HUixY8fx0qqtiypsyMH1ExHfLoRfN1H aomhbTR8+BtkzBTJuHgqweCDOvnkKn7d8QH/lwlCCFxpB5JE5xfqxG3H8V9Zk7Ao LNzEIbnri99NNyHcTvWzdLagjHPNJ5FayBrp4SY/5RXrSAZJ2+NLeS7jxZ9MkysP KJEUZmECgYEA0ye1h3abOiOWPPkqgIPw1uJ+MgMxHZZIzWXpJ7QHOvt/EAbUHJ8S no2oBfLQZhJnrNunN0poKI7J4Yq9Ts//kSiXvC6Csq0yq+b6yLv5HsgQaZ4q8sAg 4rfjlFPtHQS+QQ26UWtBtNDzxyiDT3b1tKbxNJ64JtUCEOIwp40A460CgYEAwUKB tYjEuTfiJQCLFMcYOtIk0npftwjMrOY+wY+zCePCXcQl+pSP9RNVVuZs8axBKUqz rY7ZQLPlVGDWq4eeRKuGpCfaGyaXpjt6CwPPRs3OOrQH2PSjZIGKksDyvsgnk4Ps IDgTcn9/kj5FghnBCQiEe2jPMOxFVfJ2E2nbVOkCgYEAlGlRlt/PZMLEgyCiNegG rBJPnnlN2Tza+LsLcGOBvXwtJ6eVCHTqElUAZwXuYf/HrOBKHHuI0BDkZkksm6to Nq+wTozmQg2oEtjrJZGxHGiD2KhaCXru4ktbgtKmUwIVcwXiEf3wFdXTsgSQnpa/ RfUcjd6NEoYeyJ0ik3Fw0ZUCgYB9uxQCE6nQym+hHRpe+SxlUEROfvj4bowiTGU1 rpSPcZMJR8xhmveRPPO/ZogoLqXyBDyjRJVJCADCBYKD8+ZezKz67UZzdYchyf4b Xm4ipVBvVqLoXjhS8ghCc685uaQtz5z2VSUpz5MihMrZ2oGAq/7s/wIU1RJC2UxC UxMzyQKBgHmyNHbYihZPRhqXyalf+YMDuvnsMidHF3BYgnkP7yJLFoUcsqllk38Q MFluRR6BsVwNYSCmB4t0SYmJptcTVsS68INGEoDjKYZxoiDmjsNxt2l5Kra922XS S0tBQWx8/N0DJSYeX1vqgravyuCixh55YoaS57seRDzAY528JgJm -----END RSA PRIVATE KEY-----
          source: "./html/*"
          target: "/var/www/html"
          strip_components: 1